### ISSUE TITLE
안녕하세요. 

### ISSUE THREAD

**Issue by ljlm0402** [gnokoheat/ecs-with-codepipeline-example-by-terraform#1]
안녕하세요~ 
해당 repo README에 이미지를 cloudcraft 만드신거 같은데
혹시 개인적으로 사용해도 되는지 궁금합니다.
저도 ecs 아키텍처를 그리고있는데 워낙 잘그리신거 같아서 가져가고 싶습니다 ㅎㅎ;

**Comment by gnokoheat** [comment]
아 네 안녕하세요 !
cloudcraft 로 직접 만든거 맞습니다 ㅋㅋ
마음대로 사용하셔도 되고요
혹시나 외부에 공개용도로 쓰실꺼면 출처 표기만 부탁 드리겠습니다 ^^

**Comment by ljlm0402** [comment]
@gnokoheat

감사합니다~ 잘 사용하겠습니다.
