### ISSUE TITLE
[improvement] CodeStar Source

### ISSUE THREAD

**Issue by noherczeg** [gnokoheat/ecs-with-codepipeline-example-by-terraform#3]
First of all, love the package!

Hope I can add something to improve it.

The new v2 - recommended way of wiring in Git sources is *CodeStarSourceConnection*, but the config API changed as well:

```
  stage {
    name = "Source"

    action {
      name = "Source"
      category = "Source"
      owner = "AWS"
      provider = "CodeStarSourceConnection"
      version = "1"
      output_artifacts = ["SourceArtifact"]

      configuration = {
        OutputArtifactFormat = "CODE_ZIP"
        ConnectionArn = local.github_connection_arn
        FullRepositoryId = local.github_repo
        BranchName = local.github_branch
      }
    }
  }
```

Needs additional `aws_iam_policy_document` entry as well:

```
  statement {
    sid = "AllowCodeStar"
    effect = "Allow"

    actions = [
      "codestar-connections:UseConnection"
    ]
    resources = ["*"]
  }
```

Sadly I couldn't find anything in Terraform docs how to create `github_connection_arn`... So I did it once manually, kept working after.

Edit: AWS Guideline for setting up Connections: https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-github.html#connections-github-console

**Comment by gnokoheat** [comment]
@noherczeg Hello !
Thanks for your opinion.
About two years after I wrote this code, something changes with ECS and Code pipeline.
It would be nice if you give PR with test result.
